### ISSUE TITLE
undefined reference to `wiringPiSetupPiFaceForGpioProg'

### ISSUE THREAD

**Issue by lucyking** [rm-hull/wiringPi#2]
root@raspberrypi:~/Desktop/wiringPi# ./build
wiringPi Build script
=====================

Building wiringPi with the I2C helper libraries.

WiringPi library
[UnInstall]
[Link (Dynamic + I2C)]
[Install]

GPIO Utility
[Link]
gpio.o: In function `main':
gpio.c:(.text.startup+0x154): undefined reference to `wiringPiSetupPiFaceForGpioProg'
gpio.c:(.text.startup+0x620): undefined reference to `gertboardSPISetup'
gpio.c:(.text.startup+0x634): undefined reference to `gertboardAnalogWrite'
gpio.c:(.text.startup+0x7d8): undefined reference to `gertboardSPISetup'
gpio.c:(.text.startup+0x7e8): undefined reference to `gertboardAnalogRead'
collect2: ld returned 1 exit status
Makefile:45: recipe for target 'gpio' failed
make: *** [gpio] Error 1

Make Failed...
Please check the messages and fix any problems. If you're still stuck,
then please email all the output and as many details as you can to
  projects@drogon.net

**Comment by rm-hull** [comment]
Hi, I've updated this from drogon's latest - works for me on the latest raspian - can you try again and if still now working reopen this issue.
