### ISSUE TITLE
WiringPi can now run without using sudo

### ISSUE THREAD

**Issue by DougieLawson** [rm-hull/wiringPi#3]
There's new support in WiringPi 2.29 that allows setting WIRINGPI_GPIOMEM=1 and it will use /dev/gpiomem

Can you build a new update for your forked version including the code that's been added by Gordon to add that new function? 

It looks like it's just a simple patch to wiringPi.c to add that support.

Thanks.

**Comment by rm-hull** [comment]
Hi @DougieLawson - merged latest from drogon - there were a few merge conflicts. Let me know how you get on with it

**Comment by DougieLawson** [comment]
I'll give it a go in the morning. I've got my example code running now. It reads an SQLite3 database that has some data I capture from a BMP180 temp/pressure sensor and writes five lines on my Nokia 5110.

I may push that example up to github for you.

Thank you.
